---
- name: User
  sudo: true
  sudo_user: root
  user:
    state: present
    name: scidb
    # home: "/opt/scidb"
    # system: yes
- name: SSH base directory
  sudo: true
  sudo_user: scidb
  file:
    state: directory
    path: "~/.ssh"
    mode: "0700"
- name: SSH Keys
  sudo: true
  sudo_user: scidb
  copy:
    dest: "~/.ssh/{{ item }}"
    src: "{{ item }}"
    owner: scidb
    group: scidb
    mode: 0600
  with_items:
    - id_rsa
    - id_rsa.pub
  register: ssh_keys_result
- name: SSH authorized key
  sudo: true
  sudo_user: scidb
  copy:
    dest: "~/.ssh/authorized_keys"
    src: "id_rsa.pub"
    owner: scidb
    group: scidb
    mode: 0600
